// Code generated by MockGen. DO NOT EDIT.
// Source: rand_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRand is a mock of Rand interface.
type MockRand struct {
	ctrl     *gomock.Controller
	recorder *MockRandMockRecorder
}

// MockRandMockRecorder is the mock recorder for MockRand.
type MockRandMockRecorder struct {
	mock *MockRand
}

// NewMockRand creates a new mock instance.
func NewMockRand(ctrl *gomock.Controller) *MockRand {
	mock := &MockRand{ctrl: ctrl}
	mock.recorder = &MockRandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRand) EXPECT() *MockRandMockRecorder {
	return m.recorder
}

// GetRandomCategory mocks base method.
func (m *MockRand) GetRandomCategory() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomCategory")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRandomCategory indicates an expected call of GetRandomCategory.
func (mr *MockRandMockRecorder) GetRandomCategory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomCategory", reflect.TypeOf((*MockRand)(nil).GetRandomCategory))
}

// GetRandomDifficulty mocks base method.
func (m *MockRand) GetRandomDifficulty() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomDifficulty")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRandomDifficulty indicates an expected call of GetRandomDifficulty.
func (mr *MockRandMockRecorder) GetRandomDifficulty() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomDifficulty", reflect.TypeOf((*MockRand)(nil).GetRandomDifficulty))
}

// GetRandomWord mocks base method.
func (m *MockRand) GetRandomWord(category, level int) ([]rune, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomWord", category, level)
	ret0, _ := ret[0].([]rune)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomWord indicates an expected call of GetRandomWord.
func (mr *MockRandMockRecorder) GetRandomWord(category, level interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomWord", reflect.TypeOf((*MockRand)(nil).GetRandomWord), category, level)
}
