// Code generated by MockGen. DO NOT EDIT.
// Source: user_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "handman/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUI is a mock of UI interface.
type MockUI struct {
	ctrl     *gomock.Controller
	recorder *MockUIMockRecorder
}

// MockUIMockRecorder is the mock recorder for MockUI.
type MockUIMockRecorder struct {
	mock *MockUI
}

// NewMockUI creates a new mock instance.
func NewMockUI(ctrl *gomock.Controller) *MockUI {
	mock := &MockUI{ctrl: ctrl}
	mock.recorder = &MockUIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUI) EXPECT() *MockUIMockRecorder {
	return m.recorder
}

// GetLengthInput mocks base method.
func (m *MockUI) GetLengthInput() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLengthInput")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetLengthInput indicates an expected call of GetLengthInput.
func (mr *MockUIMockRecorder) GetLengthInput() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLengthInput", reflect.TypeOf((*MockUI)(nil).GetLengthInput))
}

// ReadHiddenWord mocks base method.
func (m *MockUI) ReadHiddenWord() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadHiddenWord")
	ret0, _ := ret[0].(string)
	return ret0
}

// ReadHiddenWord indicates an expected call of ReadHiddenWord.
func (mr *MockUIMockRecorder) ReadHiddenWord() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadHiddenWord", reflect.TypeOf((*MockUI)(nil).ReadHiddenWord))
}

// ReadUserAnswer mocks base method.
func (m *MockUI) ReadUserAnswer() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUserAnswer")
	ret0, _ := ret[0].(string)
	return ret0
}

// ReadUserAnswer indicates an expected call of ReadUserAnswer.
func (mr *MockUIMockRecorder) ReadUserAnswer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUserAnswer", reflect.TypeOf((*MockUI)(nil).ReadUserAnswer))
}

// ReadUserNumber mocks base method.
func (m *MockUI) ReadUserNumber() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUserNumber")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUserNumber indicates an expected call of ReadUserNumber.
func (mr *MockUIMockRecorder) ReadUserNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUserNumber", reflect.TypeOf((*MockUI)(nil).ReadUserNumber))
}

// ReadUserRune mocks base method.
func (m *MockUI) ReadUserRune() (rune, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUserRune")
	ret0, _ := ret[0].(rune)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUserRune indicates an expected call of ReadUserRune.
func (mr *MockUIMockRecorder) ReadUserRune() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUserRune", reflect.TypeOf((*MockUI)(nil).ReadUserRune))
}

// SelectDifficultyLevel mocks base method.
func (m *MockUI) SelectDifficultyLevel() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SelectDifficultyLevel")
}

// SelectDifficultyLevel indicates an expected call of SelectDifficultyLevel.
func (mr *MockUIMockRecorder) SelectDifficultyLevel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectDifficultyLevel", reflect.TypeOf((*MockUI)(nil).SelectDifficultyLevel))
}

// SelectWordCategory mocks base method.
func (m *MockUI) SelectWordCategory() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SelectWordCategory")
}

// SelectWordCategory indicates an expected call of SelectWordCategory.
func (mr *MockUIMockRecorder) SelectWordCategory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectWordCategory", reflect.TypeOf((*MockUI)(nil).SelectWordCategory))
}

// ShowAttemptSettings mocks base method.
func (m *MockUI) ShowAttemptSettings() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowAttemptSettings")
}

// ShowAttemptSettings indicates an expected call of ShowAttemptSettings.
func (mr *MockUIMockRecorder) ShowAttemptSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowAttemptSettings", reflect.TypeOf((*MockUI)(nil).ShowAttemptSettings))
}

// ShowBadInput mocks base method.
func (m *MockUI) ShowBadInput() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowBadInput")
}

// ShowBadInput indicates an expected call of ShowBadInput.
func (mr *MockUIMockRecorder) ShowBadInput() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowBadInput", reflect.TypeOf((*MockUI)(nil).ShowBadInput))
}

// ShowCountMistakes mocks base method.
func (m *MockUI) ShowCountMistakes(countAttempts, CountMistakes int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowCountMistakes", countAttempts, CountMistakes)
}

// ShowCountMistakes indicates an expected call of ShowCountMistakes.
func (mr *MockUIMockRecorder) ShowCountMistakes(countAttempts, CountMistakes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowCountMistakes", reflect.TypeOf((*MockUI)(nil).ShowCountMistakes), countAttempts, CountMistakes)
}

// ShowDescription mocks base method.
func (m *MockUI) ShowDescription(desc string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowDescription", desc)
}

// ShowDescription indicates an expected call of ShowDescription.
func (mr *MockUIMockRecorder) ShowDescription(desc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowDescription", reflect.TypeOf((*MockUI)(nil).ShowDescription), desc)
}

// ShowDifficultyLevel mocks base method.
func (m *MockUI) ShowDifficultyLevel(diffLevel int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowDifficultyLevel", diffLevel)
}

// ShowDifficultyLevel indicates an expected call of ShowDifficultyLevel.
func (mr *MockUIMockRecorder) ShowDifficultyLevel(diffLevel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowDifficultyLevel", reflect.TypeOf((*MockUI)(nil).ShowDifficultyLevel), diffLevel)
}

// ShowError mocks base method.
func (m *MockUI) ShowError(e error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowError", e)
}

// ShowError indicates an expected call of ShowError.
func (mr *MockUIMockRecorder) ShowError(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowError", reflect.TypeOf((*MockUI)(nil).ShowError), e)
}

// ShowErrorMessage mocks base method.
func (m *MockUI) ShowErrorMessage(message string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowErrorMessage", message, err)
}

// ShowErrorMessage indicates an expected call of ShowErrorMessage.
func (mr *MockUIMockRecorder) ShowErrorMessage(message, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowErrorMessage", reflect.TypeOf((*MockUI)(nil).ShowErrorMessage), message, err)
}

// ShowHangmanPicture mocks base method.
func (m *MockUI) ShowHangmanPicture(picture string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowHangmanPicture", picture)
}

// ShowHangmanPicture indicates an expected call of ShowHangmanPicture.
func (mr *MockUIMockRecorder) ShowHangmanPicture(picture interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowHangmanPicture", reflect.TypeOf((*MockUI)(nil).ShowHangmanPicture), picture)
}

// ShowLose mocks base method.
func (m *MockUI) ShowLose() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowLose")
}

// ShowLose indicates an expected call of ShowLose.
func (mr *MockUIMockRecorder) ShowLose() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowLose", reflect.TypeOf((*MockUI)(nil).ShowLose))
}

// ShowMatchResultWord mocks base method.
func (m *MockUI) ShowMatchResultWord(word string, stat domain.Status) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowMatchResultWord", word, stat)
}

// ShowMatchResultWord indicates an expected call of ShowMatchResultWord.
func (mr *MockUIMockRecorder) ShowMatchResultWord(word, stat interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowMatchResultWord", reflect.TypeOf((*MockUI)(nil).ShowMatchResultWord), word, stat)
}

// ShowWin mocks base method.
func (m *MockUI) ShowWin() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowWin")
}

// ShowWin indicates an expected call of ShowWin.
func (mr *MockUIMockRecorder) ShowWin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowWin", reflect.TypeOf((*MockUI)(nil).ShowWin))
}

// ShowWord mocks base method.
func (m *MockUI) ShowWord(word string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowWord", word)
}

// ShowWord indicates an expected call of ShowWord.
func (mr *MockUIMockRecorder) ShowWord(word interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowWord", reflect.TypeOf((*MockUI)(nil).ShowWord), word)
}

// ShowWordCategory mocks base method.
func (m *MockUI) ShowWordCategory(category int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowWordCategory", category)
}

// ShowWordCategory indicates an expected call of ShowWordCategory.
func (mr *MockUIMockRecorder) ShowWordCategory(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowWordCategory", reflect.TypeOf((*MockUI)(nil).ShowWordCategory), category)
}
