// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "hw4-fractal-flame/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIteratedFunction is a mock of IteratedFunction interface.
type MockIteratedFunction struct {
	ctrl     *gomock.Controller
	recorder *MockIteratedFunctionMockRecorder
}

// MockIteratedFunctionMockRecorder is the mock recorder for MockIteratedFunction.
type MockIteratedFunctionMockRecorder struct {
	mock *MockIteratedFunction
}

// NewMockIteratedFunction creates a new mock instance.
func NewMockIteratedFunction(ctrl *gomock.Controller) *MockIteratedFunction {
	mock := &MockIteratedFunction{ctrl: ctrl}
	mock.recorder = &MockIteratedFunctionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIteratedFunction) EXPECT() *MockIteratedFunctionMockRecorder {
	return m.recorder
}

// RunIterations mocks base method.
func (m *MockIteratedFunction) RunIterations(cfg domain.FractalConfig) (domain.Pixels, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunIterations", cfg)
	ret0, _ := ret[0].(domain.Pixels)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunIterations indicates an expected call of RunIterations.
func (mr *MockIteratedFunctionMockRecorder) RunIterations(cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunIterations", reflect.TypeOf((*MockIteratedFunction)(nil).RunIterations), cfg)
}

// MockRandom is a mock of Random interface.
type MockRandom struct {
	ctrl     *gomock.Controller
	recorder *MockRandomMockRecorder
}

// MockRandomMockRecorder is the mock recorder for MockRandom.
type MockRandomMockRecorder struct {
	mock *MockRandom
}

// NewMockRandom creates a new mock instance.
func NewMockRandom(ctrl *gomock.Controller) *MockRandom {
	mock := &MockRandom{ctrl: ctrl}
	mock.recorder = &MockRandomMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRandom) EXPECT() *MockRandomMockRecorder {
	return m.recorder
}

// Float64n mocks base method.
func (m *MockRandom) Float64n(module float64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Float64n", module)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Float64n indicates an expected call of Float64n.
func (mr *MockRandomMockRecorder) Float64n(module interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Float64n", reflect.TypeOf((*MockRandom)(nil).Float64n), module)
}

// GetRandomFloat mocks base method.
func (m *MockRandom) GetRandomFloat(module float64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomFloat", module)
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetRandomFloat indicates an expected call of GetRandomFloat.
func (mr *MockRandomMockRecorder) GetRandomFloat(module interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomFloat", reflect.TypeOf((*MockRandom)(nil).GetRandomFloat), module)
}

// GetRandomFloatPositive mocks base method.
func (m *MockRandom) GetRandomFloatPositive(module float64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomFloatPositive", module)
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetRandomFloatPositive indicates an expected call of GetRandomFloatPositive.
func (mr *MockRandomMockRecorder) GetRandomFloatPositive(module interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomFloatPositive", reflect.TypeOf((*MockRandom)(nil).GetRandomFloatPositive), module)
}

// GetRandomIntInterval mocks base method.
func (m *MockRandom) GetRandomIntInterval(from, to int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomIntInterval", from, to)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRandomIntInterval indicates an expected call of GetRandomIntInterval.
func (mr *MockRandomMockRecorder) GetRandomIntInterval(from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomIntInterval", reflect.TypeOf((*MockRandom)(nil).GetRandomIntInterval), from, to)
}

// GetRandomIntPositive mocks base method.
func (m *MockRandom) GetRandomIntPositive(module int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomIntPositive", module)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRandomIntPositive indicates an expected call of GetRandomIntPositive.
func (mr *MockRandomMockRecorder) GetRandomIntPositive(module interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomIntPositive", reflect.TypeOf((*MockRandom)(nil).GetRandomIntPositive), module)
}

// MockVariation is a mock of Variation interface.
type MockVariation struct {
	ctrl     *gomock.Controller
	recorder *MockVariationMockRecorder
}

// MockVariationMockRecorder is the mock recorder for MockVariation.
type MockVariationMockRecorder struct {
	mock *MockVariation
}

// NewMockVariation creates a new mock instance.
func NewMockVariation(ctrl *gomock.Controller) *MockVariation {
	mock := &MockVariation{ctrl: ctrl}
	mock.recorder = &MockVariationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVariation) EXPECT() *MockVariationMockRecorder {
	return m.recorder
}

// ApplyTransform mocks base method.
func (m *MockVariation) ApplyTransform(x, y float64) (float64, float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTransform", x, y)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	return ret0, ret1
}

// ApplyTransform indicates an expected call of ApplyTransform.
func (mr *MockVariationMockRecorder) ApplyTransform(x, y interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTransform", reflect.TypeOf((*MockVariation)(nil).ApplyTransform), x, y)
}

// GetWeight mocks base method.
func (m *MockVariation) GetWeight() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeight")
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetWeight indicates an expected call of GetWeight.
func (mr *MockVariationMockRecorder) GetWeight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeight", reflect.TypeOf((*MockVariation)(nil).GetWeight))
}
